spring:
  application:
    name: nova-ai-agent
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082
