package com.nova.ai.common.event;

public enum EventType {
    AGENT_CREATED,
    AGENT_EXECUTED,
    AGENT_FAILED,
    WORKFLOW_STARTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_FAILED,
    DIGITAL_HUMAN_CREATED,
    DIGITAL_HUMAN_PUBLISHED,
    SKILL_REGISTERED,
    SKILL_EXECUTED,
    SKILL_FAILED
}
