-- Nova AI Platform Database Initialization

CREATE TABLE public.sys_user (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 name varchar(64) DEFAULT ''::character varying NOT NULL,
                                 email varchar(128) NULL,
                                 account varchar(64) NOT NULL,
                                 "password" varchar(128) NOT NULL,
                                 phone varchar(20) NULL,
                                 avatar varchar(255) NULL,
                                 user_group varchar(64) NULL,
                                 "role" varchar(64) NULL,
                                 tenant varchar(32) NULL,
                                 deleted bool DEFAULT false NOT NULL,
                                 create_user varchar(64) DEFAULT ''::character varying NOT NULL,
                                 update_user varchar(64) DEFAULT ''::character varying NOT NULL,
                                 create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 update_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_account ON sys_user(account);
CREATE INDEX IF NOT EXISTS idx_sys_user_tenant ON sys_user(tenant);

CREATE TABLE IF NOT EXISTS digital_human (
    id BIGSERIAL PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(512),
    voice_model VARCHAR(128),
    personality TEXT,
    skills JSONB,
    agent_id VARCHAR(64),
    workflow_id VARCHAR(64),
    publish_status VARCHAR(32) DEFAULT 'draft',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted BOOLEAN DEFAULT FALSE
);

CREATE INDEX idx_digital_human_user_id ON digital_human(user_id);
CREATE INDEX idx_digital_human_status ON digital_human(publish_status);
CREATE INDEX idx_digital_human_skills ON digital_human USING GIN(skills);

CREATE TABLE IF NOT EXISTS agent (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(128),
    system_prompt TEXT,
    skill_ids JSONB,
    config JSONB,
    model_id VARCHAR(64),
    temperature DOUBLE PRECISION DEFAULT 0.7,
    max_tokens INTEGER DEFAULT 2048,
    deleted BOOLEAN DEFAULT FALSE,
    create_user VARCHAR(64) DEFAULT '',
    update_user VARCHAR(64) DEFAULT '',
    created_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS workflow (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    definition JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS skill_registry (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    skill_type VARCHAR(32) NOT NULL,
    config JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS llm_model (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(32) NOT NULL DEFAULT 'openai',
    invoke_format VARCHAR(64) NOT NULL DEFAULT 'openai_chat_completions',
    remote_model VARCHAR(255) NOT NULL,
    base_url VARCHAR(512),
    api_key TEXT,
    default_temperature DOUBLE PRECISION DEFAULT 0.7,
    default_max_tokens INTEGER DEFAULT 4096,
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    description TEXT,
    extra_config JSONB DEFAULT '{}'::jsonb,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_llm_model_deleted_enabled ON llm_model(deleted, enabled);

COMMENT ON TABLE llm_model IS '注册的可调用大模型；agent.model_id 可引用 llm_model.id';
COMMENT ON COLUMN llm_model.id IS '注册表主键，供外部引用（如 agent.model_id）';
COMMENT ON COLUMN llm_model.remote_model IS '下游 API 收到的 model 字段，例如 gpt-4o-mini';
COMMENT ON COLUMN llm_model.base_url IS 'OpenAI 兼容 Chat Completions 的 base URL，通常形如 https://api.openai.com/v1；
为空则回退到配置 nova.model.providers.{provider}.base-url';
COMMENT ON COLUMN llm_model.api_key IS '明文密钥；生产环境建议改为密钥托管或 KMS，仅在此处存引用；
为空则回退到环境变量 OPENAI_API_KEY 或 nova.model.providers.openai.api-key（依 provider）';
COMMENT ON COLUMN llm_model.invoke_format IS '调用协议：当前支持 openai_chat_completions';
COMMENT ON COLUMN llm_model.extra_config IS '预留扩展头部等 JSON 配置';

