-- Nova AI Platform Database Initialization

-- public.sys_user definition

-- Drop table

-- DROP TABLE public.sys_user;

CREATE TABLE public.sys_user (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 "name" varchar(64) DEFAULT ''::character varying NOT NULL,
                                 email varchar(128) NULL,
                                 account varchar(64) NOT NULL,
                                 "password" varchar(128) NOT NULL,
                                 phone varchar(20) NULL,
                                 avatar varchar(255) NULL,
                                 user_group varchar(64) NULL,
                                 "role" varchar(64) NULL,
                                 tenant varchar(32) NULL,
                                 deleted bool DEFAULT false NOT NULL,
                                 create_user varchar(64) DEFAULT ''::character varying NOT NULL,
                                 update_user varchar(64) DEFAULT ''::character varying NOT NULL,
                                 create_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 update_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 CONSTRAINT user_pkey PRIMARY KEY (id)
);
-- public.agent definition

-- Drop table

-- DROP TABLE public.agent;

CREATE TABLE public.agent (
                              id varchar(64) NOT NULL,
                              "name" varchar(255) NOT NULL,
                              "role" varchar(128) NULL,
                              system_prompt text NULL,
                              skill_ids jsonb NULL,
                              config jsonb NULL,
                              model_id varchar(64) NULL,
                              temperature float8 DEFAULT 0.7 NULL,
                              max_tokens int4 DEFAULT 2048 NULL,
                              deleted bool DEFAULT false NULL,
                              create_user varchar(64) DEFAULT ''::character varying NULL,
                              update_user varchar(64) DEFAULT ''::character varying NULL,
                              create_date timestamp DEFAULT now() NULL,
                              update_date timestamp DEFAULT now() NULL,
                              CONSTRAINT agent_pkey PRIMARY KEY (id)
);

-- public.llm_model definition

-- Drop table

-- DROP TABLE public.llm_model;

CREATE TABLE public.llm_model (
                                  id varchar(64) NOT NULL,
                                  "name" varchar(255) NOT NULL,
                                  provider varchar(32) DEFAULT 'openai'::character varying NOT NULL,
                                  invoke_format varchar(64) DEFAULT 'openai_chat_completions'::character varying NOT NULL,
                                  remote_model varchar(255) NOT NULL,
                                  base_url varchar(512) NULL,
                                  api_key text NULL,
                                  default_temperature float8 DEFAULT 0.7 NULL,
                                  default_max_tokens int4 DEFAULT 4096 NULL,
                                  enabled bool DEFAULT true NOT NULL,
                                  description text NULL,
                                  extra_config jsonb DEFAULT '{}'::jsonb NULL,
                                  deleted bool DEFAULT false NOT NULL,
                                  create_user varchar(64) DEFAULT ''::character varying NULL,
                                  update_user varchar(64) DEFAULT ''::character varying NULL,
                                  create_date timestamp DEFAULT now() NULL,
                                  update_date timestamp DEFAULT now() NULL,
                                  CONSTRAINT llm_model_pkey PRIMARY KEY (id)
);

